<a href="https://colab.research.google.com/github/nguyen084/MATH5671/blob/master/MATH_5671_Assignment002_Group5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Source: https://github.com/ChakChak1234/FrozenLake-Using-Reinforcement-and-Tensorflow/blob/master/OpenGymAI_FrozenLake.ipynb
#The code below is modified and inspired by the source above.
from IPython.display import clear_output
import tensorflow as tf #import tensorflow
import gym
import numpy as np
import time
env = gym.make('FrozenLake-v0')


In [0]:
#Setting the parametesr
gamma = 0.8
epsilon = 0.2
episodes = 2000
alpha = 0.1
totalReward = 0
inputs1 = tf.placeholder(shape=[1,16],dtype=tf.float32) #There are total of 16 input represent 4x4 matrix
W = tf.Variable(tf.random_uniform([16,4],0,0.1)) #Initialize weights 
Q1 = tf.matmul(inputs1,W) #Getting the initial Q value
output = tf.argmax(Q1,1) #Making decision by choosing the max value

Q2 = tf.placeholder(shape=[1,4],dtype=tf.float32) #Create a placeholder for the next Q
loss = tf.reduce_sum(tf.square(Q2 - Q1)) #Loss function
gdo = tf.train.GradientDescentOptimizer(learning_rate=alpha) #Gradient decent for the lost function
updatedweights = gdo.minimize(loss) 

session = tf.Session() #Start the tensorflow session
session.run(tf.initialize_all_variables())
for i in range(episodes):
    state_now = env.reset() #Reset to state 1
    done = False
    reward = 0 #Reset the reward
    while not done: #Either reach the goal or stepped on ice
        #Start training by feeding the input
        action , Y = session.run([output, Q1], feed_dict = {inputs1 : [np.eye(16)[state_now]]})
        if epsilon > np.random.rand(1):
            action[0] = env.action_space.sample()
            epsilon -= 10**-3
        #Feed the action into the env
        state_next , reward, done, info = env.step(action[0])
        #Run the next state
        Y1 = session.run(Q1, feed_dict = {inputs1 : [np.eye(16)[state_next]]})
        change_Y = Y
        change_Y[0, action[0]] = reward + gamma*np.max(Y1)
        #Updating the weights 
        _,new_weights = session.run([updatedweights,W],feed_dict={inputs1:[np.eye(16)[state_now]],Q2:change_Y})
        #Update the reward
        totalReward += reward
        state_now = state_next
        state = state_next
session.close()
print("Average rewards: " + str(totalReward/episodes))
print(new_weights)

Average rewards: 0.047
[[0.03153995 0.03146403 0.03692959 0.03059714]
 [0.03647947 0.05054735 0.03255894 0.03711748]
 [0.03927423 0.04309006 0.06531671 0.0411752 ]
 [0.06281664 0.00269843 0.03600845 0.01536837]
 [0.04205105 0.0689192  0.04235161 0.04051131]
 [0.00636323 0.09605737 0.06818032 0.00304327]
 [0.06844991 0.09083297 0.07142799 0.02214117]
 [0.09227116 0.02762512 0.07564083 0.07379955]
 [0.04856469 0.11083631 0.03478896 0.0475601 ]
 [0.08467879 0.03189382 0.14692073 0.07191397]
 [0.23463358 0.01314266 0.03373578 0.00739723]
 [0.05090854 0.05213565 0.0887234  0.0983282 ]
 [0.05368569 0.01357607 0.05510708 0.06938589]
 [0.07258905 0.02412957 0.02439753 0.26879483]
 [0.05704917 0.01130438 0.63143975 0.06611975]
 [0.08111747 0.0783421  0.05911888 0.0294739 ]]


In [0]:
from IPython.display import clear_output
import time
env.reset()
episodes = 20
max_steps =1000

for episode in range(episodes):
    state = env.reset()
    step = 0
    done = False
    clear_output()
    print("*****************")
    print("Episodes", episode)
    print("*****************")
    
    for step in range(max_steps):        
        # Take the action that has the best Q value
        action = np.argmax(new_weights[state])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            print("*****************")
            print("Steps", step)
            print("*****************")
            time.sleep(2)
            break
        state = new_state
        
env.close()

*****************
Episodes 19
*****************
  (Down)
SFFF
FHFH
FFFH
HFFG
*****************
Steps 2
*****************
